name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install  # ou yarn install

      - name: Build Project
        run: npm run build  # ou yarn build

      - name: Deploy to Netlify
        id: deploy
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./dist"  # Remplace par ton dossier de build
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Auto-deployed via GitHub Actions"
          alias: "latest"
          enable-pull-request-comment: false
          enable-commit-comment: false
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Update README with the deployment URL
        run: |
            echo "Updating README with deployment URL..."
            DEPLOYMENT_URL="${{ steps.deploy.outputs.deploy_url }}"
            sed -i "s|DEVELOPMENT_URL|$DEPLOYMENT_URL|" README.md
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git commit -am "Update README with the latest deployment URL"
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        
